### ISSUE TITLE
A possible bug or missing fearure?

### ISSUE THREAD

**Issue by aferust** [dayllenger/beamui#17]
I am playing around with the library. My code is [here](https://gist.github.com/aferust/648ca4626f6a82c1176a455c78061047). It is a simple countdown program. I encountered a problem with state updates. In my RootWidget, I have a bool state "isWorking", and I want it to bind to "button.enabled = st.isWorking". I did not figure out how? "enabled" is not working like binding a state to a text prop. 

Another thing is that the code at line 121 causes a crash. It tries to update a state in my custom widget. The same state update is working in the code block L98 - 107. Looks like I try to modify a state before allocation?

**Comment by dayllenger** [comment]
Button becomes enabled iff it has `onClick` set. So you need to write `btn.onClick = st.isWorking ? {...} : null;`. I'll hide `enabled` in all widgets that overwrite it.

It crashes at line 121 because these widgets don't work this way. You have 3 options: controlled mode, uncontrolled, and controlled-on-demand. For example, `CheckBox` and `Slider` are controlled - they have no state, you set the value and watch changes with a callback; you keep all state in the ancestor. Uncontrolled widgets have state and don't allow to change it, only watch for changes. Controlled-on-demand (as I call it) have state, but allow to set a value if needed via field, not directly; examples are `TextField` and `ScrollBar`.

In such simple widgets it's better to use controlled mode, so basically you write:
```D
int value = 0;
void delegate(int) onChange;
...
ed1.text = to!dstring(value);
...
if (onChange)
{
    butUp.onClick = {
        if (value != max)
            onChange(.min(value + increment, max));
    };
    butDown.onClick = {
        if (value != min)
            onChange(.max(value - increment, min));
    };
    // and similarly watch for entered text changes
    // and disallow (i.e. don't fire onChange on) invalid input
}
else
    enabled = false;
```
and store all 4 values in the `RootWidget`.

**Comment by aferust** [comment]
Thank you, I will keep those in my mind.
