### ISSUE TITLE
add lib to dub package list

### ISSUE THREAD

**Issue by bubnenkoff** [dayllenger/beamui#4]
Big thanks for your lib! It's really look much better than original dlangui. Could you add it to code.dlang.org and make some announce on form.dlang.org ?

**Comment by dayllenger** [comment]
I don't want for anyone to use it today, because APIs break often, like recently I removed all style properties from Widget. I plan to publish it in 0.9.0 version, it's around in 3-4 months, I don't know surely.
First, I need to complete several researches in model-view, painting, image API, efficient formatted text rendering, well, in architecture stuff. Some parts are just not enough powerful and should be rewritten entirely. Then, I will fill up it with bunch of examples, tutorials, wiki pages. And only then I will publish.

**Comment by bubnenkoff** [comment]
Ok! I understood! Big thanks!
